#!/usr/bin/env python
# coding=UTF-8
#
# Generated by pykdeuic4 from calendar.ui on Mon Sep 28 01:31:32 2009
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui

class Ui_calendar(object):
    def setupUi(self, calendar):
        calendar.setObjectName("calendar")
        calendar.resize(256, 433)
        self.vboxlayout = QtGui.QVBoxLayout(calendar)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.kdatepicker = KDatePicker(calendar)
        self.kdatepicker.setAutoFillBackground(False)
        self.kdatepicker.setObjectName("kdatepicker")
        self.vboxlayout.addWidget(self.kdatepicker)
        self.klistwidget = KListWidget(calendar)
        self.klistwidget.setObjectName("klistwidget")
        self.vboxlayout.addWidget(self.klistwidget)
        self.klineedit = KLineEdit(calendar)
        self.klineedit.setMaxLength(1024)
        self.klineedit.setProperty("showClearButton", QtCore.QVariant(True))
        self.klineedit.setObjectName("klineedit")
        self.vboxlayout.addWidget(self.klineedit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.timeEdit = QtGui.QTimeEdit(calendar)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout.addWidget(self.timeEdit)
        self.kpushbutton = KPushButton(calendar)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../kalendar/contents/ui/tm_itemize.xpm"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kpushbutton.setIcon(icon)
        self.kpushbutton.setObjectName("kpushbutton")
        self.horizontalLayout.addWidget(self.kpushbutton)
        self.vboxlayout.addLayout(self.horizontalLayout)

        self.retranslateUi(calendar)
        QtCore.QMetaObject.connectSlotsByName(calendar)

    def retranslateUi(self, calendar):
        self.klineedit.setText(kdecore.i18n("Enter the new task here"))
        self.kpushbutton.setText(kdecore.i18n("  &Add Task"))

from PyKDE4.kdeui import KLineEdit, KPushButton, KListWidget, KDatePicker
